# DO NOT EDIT THIS FILE --- This file is a managed file, do not edit it directly.

set_target_properties(${PROJECT_NAME} PROPERTIES SUFFIX ".elf")

target_compile_options(${PROJECT_NAME} PUBLIC
    ${CPU_FLAGS}
    ${CC_SECURE}
    # Compiler flags specific to Debug build type
    $<$<CONFIG:Debug>:
      $<$<COMPILE_LANGUAGE:C>: 
        --specs=nano.specs
        -std=gnu11
        -g3
        -O0
        -Wall
        -fstack-usage
        -fcyclomatic-complexity
      >
      $<$<COMPILE_LANGUAGE:CXX>: 
        --specs=nano.specs
        -std=gnu++14
        -g3
        -O0
        -fno-use-cxa-atexit
        -Wall
        -fstack-usage
        -fcyclomatic-complexity
      >

      $<$<COMPILE_LANGUAGE:ASM>: 
        --specs=nano.specs
        -g3
        -x
        assembler-with-cpp
      >
    >

    # Compiler flags specific to Release build type
    $<$<CONFIG:Release>:
      $<$<COMPILE_LANGUAGE:C>: 
        --specs=nano.specs
        -std=gnu11
        -Os
        -Wall
        -fstack-usage
        -fcyclomatic-complexity
      >
      $<$<COMPILE_LANGUAGE:CXX>: 
        --specs=nano.specs
        -std=gnu++14
        -Os
        -fno-use-cxa-atexit
        -Wall
        -fstack-usage
        -fcyclomatic-complexity
      >

      $<$<COMPILE_LANGUAGE:ASM>: 
        --specs=nano.specs
        -x
        assembler-with-cpp
      >
    >

)

target_include_directories(${PROJECT_NAME} PUBLIC 
    "${CMAKE_CURRENT_SOURCE_DIR}/Inc"
    "${CMAKE_CURRENT_SOURCE_DIR}/Users/khs22/STM32Cube/Repository/STM32Cube_FW_F4_V1.28.3/Drivers/CMSIS/Include"
    "${CMAKE_CURRENT_SOURCE_DIR}/Users/khs22/STM32Cube/Repository/STM32Cube_FW_F4_V1.28.3/Drivers/CMSIS/Device/ST/STM32F4xx/Include"
)

target_compile_definitions(${PROJECT_NAME} PUBLIC 
    # Symbols specific to Debug build type
    $<$<CONFIG:Debug>: 
      $<$<COMPILE_LANGUAGE:C>: 
        DEBUG
        STM32
        STM32F401RETx
        STM32F401xE
        STM32F4
      >
    
      $<$<COMPILE_LANGUAGE:ASM>: 
        DEBUG
      >
    >

    
    # Symbols specific to Release build type
    $<$<CONFIG:Release>: 
      $<$<COMPILE_LANGUAGE:C>: 
        STM32
        STM32F401RETx
        STM32F4
      >
    >

    
)

target_link_options(${PROJECT_NAME} PUBLIC 
    ${CPU_FLAGS}
    ${CC_SECURE}

    # Linker flags specific to Debug build type
    $<$<CONFIG:Debug>: 
        --specs=nano.specs
        -T${CMAKE_CURRENT_BINARY_DIR}/STM32F401RETX_FLASH.ld
        --specs=nosys.specs
        -Wl,-Map=${CMAKE_CURRENT_BINARY_DIR}/automation_controller.map
        -static
    >

    # Linker flags specific to Release build type
    $<$<CONFIG:Release>: 
        --specs=nano.specs
        -T${CMAKE_CURRENT_BINARY_DIR}/STM32F401RETX_FLASH.ld
        --specs=nosys.specs
        -Wl,-Map=${CMAKE_CURRENT_BINARY_DIR}/automation_controller.map
        -static
    >

)
# Clean .map file
set_property(DIRECTORY APPEND PROPERTY ADDITIONAL_CLEAN_FILES "${CMAKE_SOURCE_DIR}/build/${CMAKE_BUILD_TYPE}/${PROJECT_NAME}.map")
