/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f401xe.h"

typedef enum
  {
      STATE_INIT = 0,
      STATE_IDLE,
      STATE_AUTO,
      STATE_DIAG,
      STATE_STOP,
      STATE_FAULT
  } system_state_t;

  static system_state_t current_state = STATE_INIT;

  static void safe_output_init(void)
    {
        RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;

        GPIOA->MODER &= ~GPIO_MODER_MODER5;
        GPIOA->MODER |= GPIO_MODER_MODER5_0;

        GPIOA->BSRR = GPIO_BSRR_BR5;
    }

  static void usart2_pins_init(void)
    {
        /* USART2 레지스터를 사용하기 전에 APB1 주변장치 클록을 활성화한다. */
        RCC->APB1ENR |= RCC_APB1ENR_USART2EN;

        /* PA2는 MODER2[1:0] = bit[5:4], PA3은 MODER3[1:0] = bit[7:6]를 사용한다.
         * GPIO_MODER_MODER2/3은 각 2비트 필드 전체(0b11)를 선택하는 마스크다.
         * ~(...)와 &= 연산으로 두 필드만 00(입력 모드)으로 지우며, 다른 핀 설정은 유지한다.
         */
        GPIOA->MODER &= ~(GPIO_MODER_MODER2 | GPIO_MODER_MODER3);





        /* PA2·PA3의 상위 모드 비트(_1)만 1로 설정한다.
         * 앞에서 두 핀의 모드 필드를 00으로 지웠으므로, 각 필드는 10이 되어
         * Alternate Function(AF) 모드가 된다.
        */
        GPIOA->MODER |= GPIO_MODER_MODER2_1 | GPIO_MODER_MODER3_1;

        /* PA2·PA3의 기존 AF 번호를 지운다. AFR[0]은 PA0~PA7의 AF 번호를 설정한다. */
        GPIOA->AFR[0] &= ~(GPIO_AFRL_AFSEL2 | GPIO_AFRL_AFSEL3);

        /* STM32F401RE의 AF 매핑에서 PA2=USART2_TX, PA3=USART2_RX는 모두 AF7이다. */
        GPIOA->AFR[0] |= (7U << GPIO_AFRL_AFSEL2_Pos);
        GPIOA->AFR[0] |= (7U << GPIO_AFRL_AFSEL3_Pos);

        /* PCLK1=16 MHz, 115200 bps, 16배 오버샘플링:
         * BRR = round(16,000,000 / 115,200) = 139 = 0x008B
         */
        USART2->CR1 = 0U;
        USART2->BRR = 139U;

        /* USART2, 송신기, 수신기 활성화 */
        USART2->CR1 = USART_CR1_UE | USART_CR1_TE | USART_CR1_RE;

    }

  static void usart2_write_char(uint8_t character)
    {
        while ((USART2->SR & USART_SR_TXE) == 0U)
        {
            /* Wait until the transmit data register is empty. */
        }

        USART2->DR = character;
    }

  static void usart2_write_text(const char *text)
    {
        while (*text != '\0')
        {
            usart2_write_char((uint8_t)*text);
            text++;
        }
    }

  static uint8_t usart2_start_command_received(void)
    {
        static const uint8_t start_command[] = "START";
        static uint8_t command_index = 0U;
        uint8_t received_byte;

        if ((USART2->SR & USART_SR_RXNE) == 0U)
        {
            return 0U;
        }

        received_byte = (uint8_t)USART2->DR;

        if ((received_byte == '\r') || (received_byte == '\n'))
        {
            if (command_index == 5U)
            {
                command_index = 0U;
                return 1U;
            }

            command_index = 0U;
            return 0U;
        }

        if ((command_index < 5U) &&
            (received_byte == start_command[command_index]))
        {
            command_index++;
        }
        else if (received_byte == start_command[0])
        {
            command_index = 1U;
        }
        else
        {
            command_index = 0U;
        }

        return 0U;
    }

  static uint8_t usart2_stop_command_received(void)
    {
        static const uint8_t stop_command[] = "STOP";
        static uint8_t command_index = 0U;
        uint8_t received_byte;

        if ((USART2->SR & USART_SR_RXNE) == 0U)
        {
            return 0U;
        }

        received_byte = (uint8_t)USART2->DR;

        if ((received_byte == '\r') || (received_byte == '\n'))
        {
            if (command_index == 4U)
            {
                command_index = 0U;
                return 1U;
            }

            command_index = 0U;
            return 0U;
        }

        if ((command_index < 4U) &&
            (received_byte == stop_command[command_index]))
        {
            command_index++;
        }
        else if (received_byte == stop_command[0])
        {
            command_index = 1U;
        }
        else
        {
            command_index = 0U;
        }

        return 0U;
    }

  int main(void)
  {
	  while (1)
	  {
		  switch (current_state)
		  {
		  case STATE_INIT:
			  safe_output_init();
			  usart2_pins_init();
			  usart2_write_text("READY\r\n");
			  current_state = STATE_IDLE;
			  break;

		  case STATE_IDLE:
			  if (usart2_start_command_received() != 0U)
			  {
				  current_state = STATE_AUTO;
				  usart2_write_text("AUTO\r\n");
			  }
			  break;

		  case STATE_AUTO:
			  if (usart2_stop_command_received() != 0U)
			  {
				  current_state = STATE_STOP;
				  usart2_write_text("STOP\r\n");
			  }
			  break;

		  case STATE_DIAG:
			  break;

		  case STATE_STOP:
			  break;

		  case STATE_FAULT:
			  break;

		  default:
			  current_state = STATE_FAULT;
			  break;
		  }
}


}
