/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f401xe.h"


typedef enum
  {
      STATE_INIT = 0,
      STATE_IDLE,
      STATE_AUTO,
      STATE_DIAG,
      STATE_STOP,
      STATE_FAULT
  } system_state_t;

  static system_state_t current_state = STATE_INIT;

  static void safe_output_init(void)
    {
        RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;

        GPIOA->MODER &= ~GPIO_MODER_MODER5;
        GPIOA->MODER |= GPIO_MODER_MODER5_0;

        GPIOA->BSRR = GPIO_BSRR_BR5;
    }

  static void usart2_pins_init(void)
    {
        RCC->APB1ENR |= RCC_APB1ENR_USART2EN;

        GPIOA->MODER &= ~(GPIO_MODER_MODER2 | GPIO_MODER_MODER3);
        GPIOA->MODER |= GPIO_MODER_MODER2_1 | GPIO_MODER_MODER3_1;

        GPIOA->AFR[0] &= ~(GPIO_AFRL_AFRL2 | GPIO_AFRL_AFRL3);
        GPIOA->AFR[0] |= (7U << GPIO_AFRL_AFRL2_Pos);
        GPIOA->AFR[0] |= (7U << GPIO_AFRL_AFRL3_Pos);
    }

  int main(void)
  {
	  while (1)
	  {
		  switch (current_state)
		  {
		  case STATE_INIT:
			  safe_output_init();
			  usart2_pins_init();
			  current_state = STATE_IDLE;
			  break;

		  case STATE_IDLE:
			  break;

		  case STATE_AUTO:
			  break;

		  case STATE_DIAG:
			  break;

		  case STATE_STOP:
			  break;

		  case STATE_FAULT:
			  break;

		  default:
			  current_state = STATE_FAULT;
			  break;
		  }
}


}
